### ISSUE TITLE
Migrating to the UnCSS organization.

### ISSUE THREAD

**Issue by giakki** [uncss/uncss#333]
Hey everyone,
Since I haven't had much time to work on the project, I was thinking about migrating to an organization in order to give more powers to the regular contributors.
While we discuss this, I'd like to set up a task list of the things that need to be done before/after the migration.

- [x] Update ghpages (tests)
- [x] Reconfigure Travis, AppVeyor, Coveralls
- [x] Update Readme (badges)
- [x] package.json

Let me know if you can think of something else, and most importantly what you think about the migration.

**Comment by RyanZim** [comment]
I'm all for the migration. I assume GH transfers all the issues and pull requests as part of the migration?

One checklist item for myself:

- [ ] Update https://github.com/RyanZim/postcss-uncss to link to the transfered repo.

Along with this, I'd be willing to consider transferring `postcss-uncss` to the uncss organization, if everyone else is OK with it.

I'm willing to try and help out with the migration. Perhaps we should add a note to the README stating that we're in the process of migrating to an organization, so people aren't worried if badges/builds are broken, etc?

**Comment by mikelambert** [comment]
Thanks for putting this up @giakki . I'm a fan of the migration, to get you off the hook for future maintainers-et-al. Your list looks pretty thorough to me.

As far as the in-progress state, according to https://help.github.com/articles/about-repository-transfers/ , all `git clone` operations will be forwarded automatically. So travis/appveyor/coveralls will continue to work during the migration, though yes the ghpages-dependent tests will fail until we fix them. I'm not too worried about a confused-users seeing broken tests, but if you want to update the readme, I'm down.

We could also explore inviting the https://github.com/ben-eb/gulp-uncss and https://github.com/addyosmani/grunt-uncss projects to the combined 'uncss' repository. @ben-eb and @addyosmani , would you be interested in this?

**Comment by RyanZim** [comment]
> We could also explore inviting the https://github.com/ben-eb/gulp-uncss and https://github.com/addyosmani/grunt-uncss projects to the combined 'uncss' repository. @ben-eb and @addyosmani , would you be interested in this?

`gulp-uncss` is deprecated, so there's no point migrating that IMO, but :+1: if `grunt-uncss` wants to migrate (not saying I'll be able to help out there, though).

**Comment by RyanZim** [comment]
@giakki Anytime you want to do the migration, go ahead IMO.

**Comment by XhmikosR** [comment]
I don't mind moving grunt-uncss under the org but we need @addyosmani's confirmation plus he's the owner so he can only make the move when we have the new organization.

**Comment by addyosmani** [comment]
I'm down with moving it over. If folks could give me a ping here or on
Twitter once the new org is good to go, happy to move it.

**Comment by XhmikosR** [comment]
@addyosmani: can you transfer the repo under the uncss organization? You can only do it since you are the owner of the repo :)

**Comment by XhmikosR** [comment]
I wonder, how are we supposed to move AppVeyor? The easy way would be for repo owners to remove and then re-add the project on AppVeyor.

**Comment by giakki** [comment]
Yeah I was just browsing the docs, and it looks like I'd need to set up a new account.
[Reference](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization)

**Comment by addyosmani** [comment]
Repo moved :)

**Comment by XhmikosR** [comment]
@giakki: thanks! I think everything is good now for grunt-uncss.

**Comment by RyanZim** [comment]
Transfered postcss-uncss in: https://github.com/uncss/postcss-uncss

@giakki could you give me admin access to that repo? The description is outdated, and I can't update it.

**Comment by XhmikosR** [comment]
Yeah, @giakki please give admin rights to Addy and me for grunt-uncss just in case it's needed.

We also need someone else with admin rights for the whole org as a backup, in case giakki goes AWOL :P

**Comment by giakki** [comment]
Done!
